import React from 'react';
import Link from 'next/link';

export function Footer() {
  return (
    <footer className="border-t border-stone-200 bg-white/60 mt-auto">
      <div className="mx-auto max-w-5xl px-4 py-8 text-xs leading-relaxed text-stone-500">
        <div className="flex flex-wrap items-center gap-x-4 gap-y-2">
          <span className="font-semibold text-stone-700">PlateUp</span>
          <Link href="/terms" className="hover:text-stone-800 hover:underline">
            Terms of Service
          </Link>
          <Link href="/privacy" className="hover:text-stone-800 hover:underline">
            Privacy Policy
          </Link>
          <a
            href="https://www.youtube.com/t/terms"
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-stone-800 hover:underline"
          >
            YouTube Terms of Service
          </a>
          <a
            href="https://policies.google.com/privacy"
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-stone-800 hover:underline"
          >
            Google Privacy Policy
          </a>
        </div>

        <p className="mt-4 max-w-3xl">
          Recipes are generated by AI from third-party videos and may be
          inaccurate. Dietary and allergen tags are automated and must not be
          relied on for allergy or medical decisions. PlateUp is not affiliated
          with, endorsed by, or sponsored by any video creator, YouTube, or
          Google.
        </p>

        <p className="mt-3 max-w-3xl">
          PlateUp participates in affiliate programs, including the Amazon
          Associates Program, and may earn commissions on qualifying purchases
          made through links on this site at no additional cost to you.
        </p>

        <p className="mt-3">
          Uses YouTube API Services.
        </p>
      </div>
    </footer>
  );
}
